### ISSUE TITLE
Please fix  MAX_EEPROM_SIZE value

### ISSUE THREAD

**Issue by plumbum** [command-tab/ch341eeprom#2]
diff --git a/ch341eeprom.h b/ch341eeprom.h
index 8ffc2d7..ddd3bdd 100644
--- a/ch341eeprom.h
+++ b/ch341eeprom.h
@@ -8,7 +8,7 @@
 #define USB_LOCK_PRODUCT            0x5512 //       (5512) CH341A in i2c mode

-#define MAX_EEPROM_SIZE             16384
+#define MAX_EEPROM_SIZE             131072

 #define BULK_WRITE_ENDPOINT         0x02
 #define BULK_READ_ENDPOINT          0x82

**Comment by paolo-caroni** [comment]
Hi at all,
since commit https://github.com/commandtab/ch341eeprom/commit/c9bb3c707e4e92b25d91eb4b6b13e3c167d4bfa4#diff-bf71490509f67512bb900bf2fad604c8 this bug is solved.
I think the bug issue can be closed,
cheers,
Paolo

**Comment by command-tab** [comment]
👍
